version: "2"

services:
  nginx:
    build: docker_setup/nginx
    image: nelisvolschenk/proxy_nginx
    env_file:
      - ./config.env
    volumes:
      - ./docker_volumes/nginx/conf:/etc/nginx/sites
      - ./docker_volumes/certbot/certs:/etc/letsencrypt
      - ./docker_volumes/certbot/acme_challenge:/var/www/certbot
      - ./docker_volumes/nginx/vhosts:/etc/nginx/vhosts
      - ./docker_volumes/nginx/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    build: docker_setup/certbot
    image: nelisvolschenk/proxy_certbot
    env_file:
      - ./config.env
    volumes:
      - ./docker_volumes/certbot/certs:/etc/letsencrypt
      - ./docker_volumes/certbot/acme_challenge:/var/www/certbot

  cron:
    build: docker_setup/cron
    image: nelisvolschenk/proxy_cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped
